# Secrets for Home Assistant
# DO NOT commit this file to git!

# Viomi V8 Vacuum
viomi_host: "192.168.1.188"
viomi_token: "ffffffffffffffffffffffffffffffff"

# Xiaomi Account
xiaomi_username: "danymirto8@gmail.com"
xiaomi_password: "FWC0yLQjm@Qi1y"

# Tuya Account
tuya_username: "danymirto8@gmail.com"
tuya_password: "Daniele2001"
